name: Java CI

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install dpl
        run: gem install dpl
  test1:
    runs-on: ubuntu-18.04
    needs: [prepare]
    steps:
      - name: Test with Maven
        working-directory: /home/runner/work/ProTester
        run: |
          ls -l
          mvn -B test
  test2:
    runs-on: ubuntu-18.04
    needs: [ prepare ]
    steps:
      - name: Test with Maven
        working-directory: /home/runner/work/ProTester/ProTester
        run: |
          ls -l
          mvn -B test
  deploy:
    runs-on: ubuntu-18.04
    needs: [test]
    steps:
      - name: Deploy to Heroku
        working-directory: /home/runner/work/ProTester
        run: dpl --provider=heroku --app=pro-tester --api-key=$HEROKU_API_KEY
