name: Java CI

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dpl
        run: gem install dpl

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test with Maven
        run: mvn test -B

      - name: Deploy to Heroku
        if: contains( github.ref, 'master')
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: dpl --provider=heroku --app=pro-tester --api-key=$HEROKU_API_KEY
